// Code generated by mockery v2.53.3. DO NOT EDIT.

package serviceaccount

import (
	prometheus "github.com/cloudogu/k8s-prometheus/auth/prometheus"
	mock "github.com/stretchr/testify/mock"
)

// Mockmanager is an autogenerated mock type for the manager type
type Mockmanager struct {
	mock.Mock
}

type Mockmanager_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockmanager) EXPECT() *Mockmanager_Expecter {
	return &Mockmanager_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateServiceAccount provides a mock function with given fields: consumer, params, behaviorParams
func (_m *Mockmanager) CreateOrUpdateServiceAccount(consumer string, params map[string]string, behaviorParams prometheus.BehaviorParams) (map[string]string, prometheus.CredentialChangeType, error) {
	ret := _m.Called(consumer, params, behaviorParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateServiceAccount")
	}

	var r0 map[string]string
	var r1 prometheus.CredentialChangeType
	var r2 error
	if rf, ok := ret.Get(0).(func(string, map[string]string, prometheus.BehaviorParams) (map[string]string, prometheus.CredentialChangeType, error)); ok {
		return rf(consumer, params, behaviorParams)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string, prometheus.BehaviorParams) map[string]string); ok {
		r0 = rf(consumer, params, behaviorParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string, prometheus.BehaviorParams) prometheus.CredentialChangeType); ok {
		r1 = rf(consumer, params, behaviorParams)
	} else {
		r1 = ret.Get(1).(prometheus.CredentialChangeType)
	}

	if rf, ok := ret.Get(2).(func(string, map[string]string, prometheus.BehaviorParams) error); ok {
		r2 = rf(consumer, params, behaviorParams)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Mockmanager_CreateOrUpdateServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateServiceAccount'
type Mockmanager_CreateOrUpdateServiceAccount_Call struct {
	*mock.Call
}

// CreateOrUpdateServiceAccount is a helper method to define mock.On call
//   - consumer string
//   - params map[string]string
//   - behaviorParams prometheus.BehaviorParams
func (_e *Mockmanager_Expecter) CreateOrUpdateServiceAccount(consumer interface{}, params interface{}, behaviorParams interface{}) *Mockmanager_CreateOrUpdateServiceAccount_Call {
	return &Mockmanager_CreateOrUpdateServiceAccount_Call{Call: _e.mock.On("CreateOrUpdateServiceAccount", consumer, params, behaviorParams)}
}

func (_c *Mockmanager_CreateOrUpdateServiceAccount_Call) Run(run func(consumer string, params map[string]string, behaviorParams prometheus.BehaviorParams)) *Mockmanager_CreateOrUpdateServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]string), args[2].(prometheus.BehaviorParams))
	})
	return _c
}

func (_c *Mockmanager_CreateOrUpdateServiceAccount_Call) Return(credentials map[string]string, changed prometheus.CredentialChangeType, err error) *Mockmanager_CreateOrUpdateServiceAccount_Call {
	_c.Call.Return(credentials, changed, err)
	return _c
}

func (_c *Mockmanager_CreateOrUpdateServiceAccount_Call) RunAndReturn(run func(string, map[string]string, prometheus.BehaviorParams) (map[string]string, prometheus.CredentialChangeType, error)) *Mockmanager_CreateOrUpdateServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServiceAccount provides a mock function with given fields: consumer
func (_m *Mockmanager) DeleteServiceAccount(consumer string) error {
	ret := _m.Called(consumer)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(consumer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockmanager_DeleteServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceAccount'
type Mockmanager_DeleteServiceAccount_Call struct {
	*mock.Call
}

// DeleteServiceAccount is a helper method to define mock.On call
//   - consumer string
func (_e *Mockmanager_Expecter) DeleteServiceAccount(consumer interface{}) *Mockmanager_DeleteServiceAccount_Call {
	return &Mockmanager_DeleteServiceAccount_Call{Call: _e.mock.On("DeleteServiceAccount", consumer)}
}

func (_c *Mockmanager_DeleteServiceAccount_Call) Run(run func(consumer string)) *Mockmanager_DeleteServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Mockmanager_DeleteServiceAccount_Call) Return(_a0 error) *Mockmanager_DeleteServiceAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockmanager_DeleteServiceAccount_Call) RunAndReturn(run func(string) error) *Mockmanager_DeleteServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceAccount provides a mock function with given fields: consumer
func (_m *Mockmanager) GetServiceAccount(consumer string) (map[string]string, bool, error) {
	ret := _m.Called(consumer)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceAccount")
	}

	var r0 map[string]string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (map[string]string, bool, error)); ok {
		return rf(consumer)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(consumer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(consumer)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(consumer)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Mockmanager_GetServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceAccount'
type Mockmanager_GetServiceAccount_Call struct {
	*mock.Call
}

// GetServiceAccount is a helper method to define mock.On call
//   - consumer string
func (_e *Mockmanager_Expecter) GetServiceAccount(consumer interface{}) *Mockmanager_GetServiceAccount_Call {
	return &Mockmanager_GetServiceAccount_Call{Call: _e.mock.On("GetServiceAccount", consumer)}
}

func (_c *Mockmanager_GetServiceAccount_Call) Run(run func(consumer string)) *Mockmanager_GetServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Mockmanager_GetServiceAccount_Call) Return(user map[string]string, found bool, err error) *Mockmanager_GetServiceAccount_Call {
	_c.Call.Return(user, found, err)
	return _c
}

func (_c *Mockmanager_GetServiceAccount_Call) RunAndReturn(run func(string) (map[string]string, bool, error)) *Mockmanager_GetServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmanager creates a new instance of Mockmanager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmanager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockmanager {
	mock := &Mockmanager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
