apiVersion: v1
values:
  images:
    kubeStateMetrics: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
    prometheusNodeExporter: quay.io/prometheus/node-exporter:v1.7.0
    configmapReloader: quay.io/prometheus-operator/prometheus-config-reloader:v0.71.2
    prometheusServer: quay.io/prometheus/prometheus:v2.50.1
    configInitContainer: busybox:1.36
    saProviderSidecar: k3ces.local:30099/k8s-prometheus:2.50.1-1
patches:
  values.yaml:
    prometheus:
      kube-state-metrics:
        enabled: true
        image:
          registry: "{{ registryFrom .images.kubeStateMetrics }}"
          repository: "{{ repositoryFrom .images.kubeStateMetrics }}"
          tag: "{{ tagFrom .images.kubeStateMetrics }}"
      alertmanager:
        enabled: false
      prometheus-node-exporter:
        enabled: true
        image:
          registry: "{{ registryFrom .images.prometheusNodeExporter }}"
          repository: "{{ repositoryFrom .images.prometheusNodeExporter }}"
          tag: "{{ tagFrom .images.prometheusNodeExporter }}"
      configmapReload:
        prometheus:
          image:
            repository: "{{ registryFrom .images.configmapReloader }}/{{ repositoryFrom .images.configmapReloader }}"
            tag: "{{ tagFrom .images.configmapReloader }}"
      server:
        image:
          repository: "{{ registryFrom .images.prometheusServer }}/{{ repositoryFrom .images.prometheusServer }}"
          tag: "{{ tagFrom .images.prometheusServer }}"
      sidecarContainers:
        serviceaccount:
          image: "{{ registryFrom .images.saProviderSidecar }}/{{ repositoryFrom .images.saProviderSidecar }}:{{ tagFrom .images.saProviderSidecar }}"
      extraInitContainers:
        - name: config-init
          image: "{{ registryFrom .images.configInitContainer }}/{{ repositoryFrom .images.configInitContainer }}:{{ tagFrom .images.configInitContainer }}"
          command:
            - 'sh'
            - '-c'
            - 'cp -n /initial-config/web.config.yaml /config/web.config.yaml'
          volumeMounts:
            - name: ces-config
              mountPath: /config
            - name: initial-config
              mountPath: /initial-config
