{{ $username := "promethues-user" }}
{{ $password :=  randAlphaNum 24  }}
apiVersion: v1
kind: Secret
metadata:
  name: "k8s-prometheus-auth-secret"
  labels:
    app: ces
    app.kubernetes.io/name: k8s-prometheus
type: Opaque
data:
  username: {{ $username | b64enc }}
  password: {{ $password | b64enc }}
stringData:
  web.config.yaml: |
    basic_auth_users:
      {{ $username }}: "{{ bcrypt $password }}"