{{- if and .Values.global.networkPolicies.enabled .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kube-prometheus-stack.name" . }}-exposed-ingress
  labels:
    {{- include "prometheus.node-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus.server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ecosystem
      podSelector:
        matchLabels:
          k8s.cloudogu.com/component.name: k8s-ces-gateway
    ports:
      - port: auth-proxy
        protocol: TCP
{{- end }}