apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: k8s-prometheus
spec:
  podSelector:
    matchLabels:
      app: k8s-prometheus
      k8s-prometheus: prometheus-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: { }
      ports:
        - port: 8086
          protocol: TCP
        - port: 8087
          protocol: TCP
