{{- if .Values.global.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kube-prometheus-stack.name" . }}-node-exporter-allow-prometheus-server
  labels:
    {{- include "prometheus.node-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus.node-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "prometheus.server.selectorLabels" . | nindent 12 }}
{{- end }}