{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kube-prometheus-stack.name" . }}-prometheus-allow-component-operator
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus.server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: k8s-dogu-operator
      ports:
        - port: 8086
          protocol: TCP
        - port: 8087
          protocol: TCP
{{- end }}