{{- if .Values.global.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kube-prometheus-stack.name" . }}-prometheus-operator-deny-all
  labels:
    {{- include "prometheus.operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus.operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress: []
{{- end }}