apiVersion: v1
kind: Secret
metadata:
  name: "k8s-prometheus-service-account-api"
  labels:
    app: ces
    app.kubernetes.io/name: k8s-prometheus
type: Opaque
data:
  apiKey: {{ randAlphaNum 24 | b64enc }}